#ifndef _PARAM_PERL_H_
#define _PARAM_PERL_H_

// this file is automatically generated by a perl script
// do not modify it

#define TEST1
#define TEST2
#define TEST3
#define TEST4
#define TEST5
#define TEST6
#define TEST7
#define TEST8
#define TEST9
#define TEST10
#define TEST11
#define TEST12
#define TEST13
#define TEST14
#define TEST15
#define TEST16
#define TEST17
#define TEST18
#define TEST19
#define TEST20
#define TEST21
#define TEST22
#define TEST23
#define TEST24
#define TEST25
#define TEST26
#define TEST27
#define TEST28
#define TEST29
#define TEST30
#define TEST31
#define TEST32

#endif //PARAM_PERL_H_
